export const GET_POKEMONS = "GET_POKEMONS"
export const GET_INFORMATION_POKEMON = "GET_INFORMATION_POKEMON"

export const GET_SKILL = "GET_SKILL"

export const FILTERED_POKEMON = "FILTERED_POKEMON"

export const CHANGE_SKILL_LOADING = "CHANGE_SKILL_LOADING"
export const CHANGE_LIST_POKEMON_LOADING = "CHANGE_LIST_POKEMON_LOADING"
export const CHANGE_POKEMON_LOADING = "CHANGE_POKEMON_LOADING"
